name: Run Gradle on PRs
on:
  pull_request:
  push:
jobs:
  gradle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra:
          - "11.1"
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: antoniovazquezblanco/setup-ghidra@v1.2.3
      with:
        auth_token: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ matrix.ghidra }}
    - name: Execute Gradle build
      run: ./gradlew -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./dist/GameCubeLoader-*.zip
