name: Run Gradle on PRs
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: antoniovazquezblanco/setup-ghidra@v2.0.6
      with:
        auth_token: ${{ secrets.GITHUB_TOKEN }}
        version: 11.3
    - name: Execute Gradle build
      run: ./gradlew -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./dist/GameCubeLoader-*.zip
